site_name: 交流会ドキュメントサイト

nav :
  - Home:         index.md
  - 開発環境:
    - Info:       dev/info.md
    - Git:        dev/git.md
    - Swagger:    dev/swagger.md
  - WEB APP:
    - Info:       app/info.md
    - REST API:   app/restapi.md
  - 言語:
    - Info:       lang/info.md
    - JavaScript: lang/js_study.md
    - React.js:
      - React(過去): lang/js_react.md
    - C++:        lang/cpuls_study.md
  - DocumentInfo: document_info.md

theme:
  name: material
  language: ja
  features:
    - tabs   # タブ表示を有効化.
  font:
    text: Noto Sans JP

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

extra_css:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

